name: End-to-end tests
on: [push]
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: install
        run: |
          npm install
      - name: build
        run: |
          npm run start
      - name: uat
        run: |
          npx serve _site -l 3000 &
          npx cypress run --record false
        
