name: Node CI
on: [push]
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      # Install NPM dependencies
      # and run all Cypress tests
      - name: cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm run strt:ci
          record: false
